export const GET_USERS = "GET_USERS";
export const GET_USERS_SAGA = "GET_USERS_SAGA";

export const FETCHING_USERS_STATUS_PENDING = "FETCHING_USERS_STATUS_PENDING";
export const FETCHING_USERS_STATUS_SUCCESS = "FETCHING_USERS_STATUS_SUCCESS";
export const FETCHING_USERS_STATUS_ERROR = "FETCHING_USERS_STATUS_ERROR";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SAGA = "ADD_USER_SAGA";

export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_SAGA = "REMOVE_USER_SAGA";
