export const GET_USERS = "GET_USERS";
export const GET_USERS_SAGA = "GET_USERS_SAGA";

export const FETCHING_USERS_STATUS_PENDING = "FETCHING_USERS_STATUS_PENDING";
export const FETCHING_USERS_STATUS_SUCCESS = "FETCHING_USERS_STATUS_SUCCESS";
export const FETCHING_USERS_STATUS_ERROR = "FETCHING_USERS_STATUS_ERROR";
