const RANDOM_PRODUCTS_QUANTITY_IN_CAROUSEL = 3;
const RANDOM_PRODUCTS_QUANTITY_IN_RELATED_PRODUCTS = 5;

export {
  RANDOM_PRODUCTS_QUANTITY_IN_CAROUSEL,
  RANDOM_PRODUCTS_QUANTITY_IN_RELATED_PRODUCTS,
};
