export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SAGA = "GET_PRODUCTS_SAGA";

export const FETCHING_PRODUCT_STATUS_PENDING =
  "FETCHING_PRODUCT_STATUS_PENDING";
export const FETCHING_PRODUCT_STATUS_SUCCESS =
  "FETCHING_PRODUCT_STATUS_SUCCESS";
export const FETCHING_PRODUCT_STATUS_ERROR = "FETCHING_PRODUCT_STATUS_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SAGA = "ADD_PRODUCT_SAGA";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_SAGA = "REMOVE_PRODUCT_SAGA";
